<h1> Q1: Linear Regression </h1>

In [1]:
import os
import autograd.numpy as np  # when testing gradient
from cvxopt import matrix, solvers
import pandas as pd


In [6]:
#Q1a)

def minimizeL2(X,y):
    #from lecture, we know the analytic solution to L2 loss
    # is   w = ((XtX)^-1)Xty

    x_trans = X.T

    #(XtX)^-1
    firstpart = np.linalg.inv(x_trans @ X)
    #secondpart XtY
    secpart = np.dot(x_trans, y)

    return (firstpart @ secpart)


# Sample data for testing
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([7, 8, 9])    
    
    
# Test the function
w = minimize(X, y)
print("Weights w:", w)

# Check if the result makes sense by calculating X @ w and comparing with y
y_pred = X @ w
print("Predicted y:", y_pred)
print("Original y:", y)


Weights w: [-6.   6.5]
Predicted y: [7. 8. 9.]
Original y: [7 8 9]


In [10]:
#Q1b)

def minimizeL1(X,y):

    n, d = X.shape
    Identity = np.eye(n)
    nOnes = np.ones(n)
    objfunc = np.concatenate([np.zeros(d), nOnes])  # [0's for w, 1's for delta]

    #constraints
    con1 = np.hstack([X, -Identity])  #Xw - y <= delta
    con2 = np.hstack([-X, -Identity])  #y - Xw <= delta
    constraints = np.vstack([con1, con2]) #combine to make the constraint array

    #y portion of |Xw-y| < delta
    h1 = y   #Xw - delta <= y
    h2 = -y   #y-Xw - delta <= -y
    h = np.concatenate([h1,h2])
    h = h.reshape(-1, 1) #turn to col vector
    h = matrix(h, tc='d')  # Ensure h is a cvxopt matrix in double precision

    constraints_cvxopt = matrix(constraints)
    h_cvxopt = matrix(h)
    objfunc_cvxopt = matrix(objfunc)

    solvers.options['show_progress'] = False  # Silence solver output
    solution = solvers.lp(objfunc_cvxopt, constraints_cvxopt, h_cvxopt)

    return np.array(solution['x'])[:d]


# Testing the function
X = np.array([[1, 2], [2, 3], [3, 4]])  # 3 samples, 2 features
y = np.array([1, 2, 3])  # Target values

w = minimizeL1(X, y)

print("Computed weights (w) \n:", w)

y_pred = X @ w 
print("Predicted y: \n", y_pred)
print("Original y: \n", y)

l1_loss = np.sum(np.abs(y - y_pred))
print("L1 loss:", l1_loss)


Computed weights (w) 
: [[1.00000000e+00]
 [2.56881886e-16]]
Predicted y: 
 [[1.]
 [2.]
 [3.]]
Original y: 
 [1 2 3]
L1 loss: 8.0


In [16]:
#Q1c)

def minimizeLinf(X, y):
    
    n, d = X.shape  # n: number of data points, d: number of features
    objfunc = np.concatenate([np.zeros(d), [1]])  # Objective: [0's for w, 1 for delta]
    Identity = np.eye(n)

    
    con1 = np.hstack([X, -np.ones((n, 1))])   # Xw - delta <= y
    con2 = np.hstack([-X, -np.ones((n, 1))])  # y - Xw <= delta
    constraints = np.vstack([con1, con2])

    # y portion of |Xw - y| <= delta
    h1 = y  # Xw - y <= delta)
    h2 = -y  # y - Xw <= delta)
    h = np.concatenate([h1, h2])

    constraints_cvxopt = matrix(constraints, tc='d')
    h_cvxopt = matrix(h, tc='d')
    objfunc_cvxopt = matrix(objfunc, tc='d')

    solvers.options['show_progress'] = False
    solution = solvers.lp(objfunc_cvxopt, constraints_cvxopt, h_cvxopt)

    # Return the optimized weights (w), which are the first d elements of the solution
    return np.array(solution['x'])[:d]


# Testing the function
X = np.array([[1, 2], [2, 3], [3, 4]])  # 3 samples, 2 features
y = np.array([1, 2, 3])  # Target values

w = minimizeLinf(X, y)

print("Computed weights (w) \n:", w)

y_pred = X @ w 
print("Predicted y: \n", y_pred)
print("Original y: \n", y)

l1_loss = np.sum(np.abs(y - y_pred))
print("Linf loss:", l1_loss)

Computed weights (w) 
: [[1.00000000e+00]
 [5.89705064e-17]]
Predicted y: 
 [[1.]
 [2.]
 [3.]]
Original y: 
 [1 2 3]
Linf loss: 8.0


In [ ]:
#d
